name: estreams
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - jedi=0.19.1
  - jupyterlab=3.6.2
  - matplotlib=3.8.3
  - networkx
  - pip=24.0
  - python=3.9.18
  - rasterio=1.3.9
  - shapely
  - textdistance
  - tqdm
  - pip:
      - cftime==1.6.3
      - netcdf4==1.6.2
      - numpy==1.24.4
      - openpyxl==3.1.0
      - pandas==2.1.3
      - pyet==1.2.2
      - scipy==1.9.0
      - xarray==2024.2.0
      - selenium==4.23.1
      - tabula
      - lxml==5.2.2